#!/usr/bin/env ruby
# frozen_string_literal: true

TAG="auto_labelling_api"

system("git remote update > /dev/null 2>&1")
outdated = `git status -uno`.include?("Your branch is behind")

if outdated || ARGV.include?("--force")
    puts "Starting update at #{Time.now}"
    system("git pull")
    system("docker stop #{TAG} > /dev/null 2>&1 || true")
    system("docker build . --compress --tag #{TAG}")
    system("docker run --rm -d -it -p 5000:5000 --name #{TAG} --rm #{TAG}")
    puts "Finishing update at #{Time.now}"
end
